name=FLProg Modbus
version=1.0.0
author=FLProg
maintainer=Flprog <support@flprog.ru>
sentence=Arduino library for modbus
paragraph=Arduino library for modbus
category=Communication
url=https://flprog.ru
architectures=*
repository=https://flprog.ru/node-repo.git
depends=flprogUtilites 

#repository=https://[gitlab-address]/node-repo.git
