name=FLProg Modbus
version=1.0.0
author=FLProg
maintainer=Flprog <support@flprog.ru>
sentence=Arduino library for modbus
paragraph=Arduino library for modbus
category=Communication
url=https://flprog.ru
architectures=*
repository=https://github.com/Totuin/Flprog_Modbus.git
depends=flprogUtilites 


